# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole website, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Christian Worship: Handbook'
email: caleb.bassett@gmail.com
description: 'A public handbook of research information about the hymns published in Christian Worship: Hymnal.'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://master.d3tlpociqdd60v.amplifyapp.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
  sass_dir: css
collections_dir: collections
collections:
  texts:
    output: true
    permalink: /text/:name
  tunes:
    output: true
    permalink: /tune/:title
  authors:
    output: true
    permalink: /author/:name
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
